# Generated by Django 3.2.4 on 2021-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yqmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=24, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ways',
            field=models.CharField(max_length=50, verbose_name='走过的省份'),
        ),
    ]
